/*************************************************************************
**	Chrz¹szcz Prototype													**
*************************************************************************/

PROTOTYPE Mst_Bug(C_Npc)			
{
	name							=	"Panceryny Chrz¹szcz";
	guild							=	GIL_MINECRAWLER;
	aivar[AIV_MM_REAL_ID]			= 	ID_BUG;
	level							=	6;

//------------------------------------------------------------
	attribute	[ATR_STRENGTH]		=	36;
	attribute	[ATR_DEXTERITY]		=	36;
	
	attribute	[ATR_HITPOINTS_MAX]	=	42;
	attribute	[ATR_HITPOINTS]		=	42;

	attribute	[ATR_MANA_MAX] 		=	0;
	attribute	[ATR_MANA] 			=	0;
//------------------------------------------------------------
	protection	[PROT_BLUNT]		=	20;
	protection	[PROT_EDGE]			=	20;
	protection	[PROT_POINT]		=	20;
	protection	[PROT_FIRE]			=	50;
	protection	[PROT_FLY]			=	10;
	protection	[PROT_MAGIC]		=	5;
//------------------------------------------------------------
	damagetype 						=	DAM_EDGE;
//	damage		[DAM_INDEX_BLUNT]	=	0;
//	damage		[DAM_INDEX_EDGE]	=	0;
//	damage		[DAM_INDEX_POINT]	=	0;
//	damage		[DAM_INDEX_FIRE]	=	0;
//	damage		[DAM_INDEX_FLY]		=	0;
//	damage		[DAM_INDEX_MAGIC]	=	0;
//------------------------------------------------------------
	fight_tactic					=	FAI_MINECRAWLER;
//------------------------------------------------------
	senses						= SENSE_HEAR | SENSE_SEE | SENSE_SMELL;
	senses_range				= 1750;

	aivar[AIV_MM_Behaviour]		= PACKHUNTER;
	
	aivar[AIV_MM_PercRange]		= 1200;
	aivar[AIV_MM_DrohRange]		= 1200;
	aivar[AIV_MM_AttackRange]	= 1000;
	aivar[AIV_MM_DrohTime]		= 2;
	aivar[AIV_MM_FollowTime]	= 10;
	aivar[AIV_MM_FollowInWater] = FALSE;
//---------------------------------------------------
	start_aistate				= ZS_MM_AllScheduler;

	aivar[AIV_MM_WuselStart] 	= OnlyRoutine;
};
//---------------------------------------------------
//------------------------------------------------------------
func void Set_Bug_Visuals()
{
	Mdl_SetVisual			(self,"Giant_Bug.mds");
	//								Body-Mesh		Body-Tex	Skin-Color	Head-MMS	Head-Tex	Teeth-Tex	ARMOR
	Mdl_SetVisualBody		(self,	"Giant_Bug_Body",		DEFAULT,	DEFAULT,	"",			DEFAULT,  	DEFAULT,	-1);
	Mdl_SetModelScale(self, 0.3, 0.3, 0.3);
};

INSTANCE Bug	(Mst_Bug)
{
	Set_Bug_Visuals();
	Npc_SetToFistMode(self);
};

